version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install PDM
      - pip install pdm
    post_install:
      # Install dependencies with 'docs' dependency group
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH pdm install -G docs

sphinx:
  configuration: docs/conf.py
