name: Upload Python Package

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    if: "contains(github.event.head_commit.message, '[make release]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Bump and Update Changelog
      uses: commitizen-tools/commitizen-action@0.14.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        changelog_increment_filename: body.md

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: body.md
        tag_name: ${{ env.REVISION }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '>=3.8'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Publish Package
      env:
        PYPI_USERNAME: __token__
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry publish --build -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD"
