name: Testing

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Do it
      run: echo "hello world"
